name: Merge any release branch to uat
on:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge main -> develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: develop
          github_token: ${{ github.token }}
